import { ICON_PALETTE, mascot, type Part, type Role } from '../apps/mobile/src/design/mascot';

/**
 * Serialises the mascot's parts to an SVG document. The renderer and the React
 * component both read `mascot.ts`; this file exists only to turn parts into the
 * text a rasteriser can take.
 */
function paint(role: Role | undefined): string | undefined {
  return role ? ICON_PALETTE[role] : undefined;
}

/**
 * Whether a path's `d` has more than one drawn segment after the initial
 * `M` — i.e. an interior vertex a `stroke-linejoin` could round. `Z` is
 * excluded: every closed path here already returns to its `M` point via its
 * last drawn segment, so the close is a zero-length no-op, not a corner.
 */
function hasInteriorVertex(d: string): boolean {
  const commands = (d.match(/[A-Za-z]/g) ?? []).filter((c) => c !== 'M' && c.toUpperCase() !== 'Z');
  return commands.length > 1;
}

/**
 * `stroke-linecap` and `stroke-linejoin` are omitted, not defaulted to
 * `"round"`, wherever the hand-authored SVG this replaces omitted them: never
 * on a circle or ellipse, never `linecap` on a closed path (it has no open
 * ends to cap), never `linejoin` on a path with only one drawn segment (it
 * has no interior vertex to join). That is not a cosmetic choice — resvg's
 * stroke-to-fill tessellation for a closed shape renders a few pixels
 * differently at favicon size depending on whether these attributes are
 * present at all, even though neither one changes the geometry. Adding them
 * unconditionally is what `scripts/compare-pngs.ts` catches: byte-identical
 * at 1024px, a real difference at 48px.
 */
function attrs(part: Part): string {
  const out: string[] = [];
  out.push(`fill="${paint(part.fill) ?? 'none'}"`);
  if (part.stroke) {
    out.push(`stroke="${paint(part.stroke)}"`);
    out.push(`stroke-width="${part.width ?? 26}"`);
    if (part.kind === 'path') {
      if (!part.closed) out.push('stroke-linecap="round"');
      if (hasInteriorVertex(part.d)) out.push('stroke-linejoin="round"');
    }
  }
  if (part.transform) out.push(`transform="${part.transform}"`);
  return out.join(' ');
}

export function elementFor(part: Part): string {
  const shared = attrs(part);
  switch (part.kind) {
    case 'path':
      return `<path d="${part.d}" ${shared}/>`;
    case 'circle':
      return `<circle cx="${part.cx}" cy="${part.cy}" r="${part.r}" ${shared}/>`;
    case 'ellipse':
      return `<ellipse cx="${part.cx}" cy="${part.cy}" rx="${part.rx}" ry="${part.ry}" ${shared}/>`;
  }
}

export function markSvg(): string {
  const { parts, viewBox, transform } = mascot('carrying');
  const body = parts.map(elementFor).join('\n    ');
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="1024" height="1024">`,
    '  <!-- Generated by scripts/render-icons.ts from src/design/mascot.ts. Do not edit. -->',
    `  <g transform="${transform}">`,
    `    ${body}`,
    '  </g>',
    '</svg>',
    '',
  ].join('\n');
}
