import {
  COIN_TRANSFORM,
  ICON_PALETTE,
  mascot,
  MONO_CUTS,
  type Part,
  type Role,
} from '../apps/mobile/src/design/mascot';

/**
 * Serialises the mascot's parts to an SVG document. The renderer and the React
 * component both read `mascot.ts`; this file exists only to turn parts into the
 * text a rasteriser can take.
 */
function paint(role: Role | undefined): string | undefined {
  return role ? ICON_PALETTE[role] : undefined;
}

/**
 * Whether a path's `d` has more than one drawn segment after the initial
 * `M` — i.e. an interior vertex a `stroke-linejoin` could round. `Z` is
 * excluded: every closed path here already returns to its `M` point via its
 * last drawn segment, so the close is a zero-length no-op, not a corner.
 */
function hasInteriorVertex(d: string): boolean {
  const commands = (d.match(/[A-Za-z]/g) ?? []).filter((c) => c !== 'M' && c.toUpperCase() !== 'Z');
  return commands.length > 1;
}

/**
 * `stroke-linecap` and `stroke-linejoin` are omitted, not defaulted to
 * `"round"`, wherever the hand-authored SVG this replaces omitted them: never
 * on a circle or ellipse, never `linecap` on a closed path (it has no open
 * ends to cap), never `linejoin` on a path with only one drawn segment (it
 * has no interior vertex to join). That is not a cosmetic choice — resvg's
 * stroke-to-fill tessellation for a closed shape renders a few pixels
 * differently at favicon size depending on whether these attributes are
 * present at all, even though neither one changes the geometry. Adding them
 * unconditionally is what `scripts/compare-pngs.ts` catches: byte-identical
 * at 1024px, a real difference at 48px.
 */
function attrs(part: Part): string {
  const out: string[] = [];
  out.push(`fill="${paint(part.fill) ?? 'none'}"`);
  if (part.stroke) {
    out.push(`stroke="${paint(part.stroke)}"`);
    out.push(`stroke-width="${part.width ?? 26}"`);
    if (part.kind === 'path') {
      if (!part.closed) out.push('stroke-linecap="round"');
      if (hasInteriorVertex(part.d)) out.push('stroke-linejoin="round"');
    }
  }
  if (part.transform) out.push(`transform="${part.transform}"`);
  return out.join(' ');
}

export function elementFor(part: Part): string {
  const shared = attrs(part);
  switch (part.kind) {
    case 'path':
      return `<path d="${part.d}" ${shared}/>`;
    case 'circle':
      return `<circle cx="${part.cx}" cy="${part.cy}" r="${part.r}" ${shared}/>`;
    case 'ellipse':
      return `<ellipse cx="${part.cx}" cy="${part.cy}" rx="${part.rx}" ry="${part.ry}" ${shared}/>`;
  }
}

export function markSvg(): string {
  const { parts, viewBox, transform } = mascot('carrying');
  const body = parts.map(elementFor).join('\n    ');
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="1024" height="1024">`,
    '  <!-- Generated by scripts/render-icons.ts from src/design/mascot.ts. Do not edit. -->',
    `  <g transform="${transform}">`,
    `    ${body}`,
    '  </g>',
    '</svg>',
    '',
  ].join('\n');
}

/**
 * The monochrome layer for Android, which keeps only the alpha channel and
 * tints it one colour. An outline is the one thing a single flat colour cannot
 * express: fill it in and coin, segments, legs and face fuse into one lump. So
 * the ink becomes a gap — every shape is filled solid out to the outer edge of
 * its stroke, then the seams are cut back out as holes in a mask.
 *
 * Every width and every cut here comes from `mascot.ts`. Nothing about the
 * mark's shape is decided in this file.
 */
function solidElement(part: Part): string {
  const attrs: string[] = [];
  if (!part.fill) attrs.push('fill="none"');
  if (part.monoStroke === 0) attrs.push('stroke="none"');
  else if (part.monoStroke !== undefined) attrs.push(`stroke-width="${part.monoStroke}"`);
  if (part.transform) attrs.push(`transform="${part.transform}"`);
  const tail = attrs.join(' ');
  switch (part.kind) {
    case 'path':
      return `<path d="${part.d}" ${tail}/>`;
    case 'circle':
      return `<circle cx="${part.cx}" cy="${part.cy}" r="${part.monoRadius ?? part.r}" ${tail}/>`;
    case 'ellipse':
      return `<ellipse cx="${part.cx}" cy="${part.cy}" rx="${part.rx}" ry="${part.ry}" ${tail}/>`;
  }
}

export function monoSvg(): string {
  const { parts, viewBox, transform } = mascot('carrying');
  const byId = (id: string) => parts.find((part) => part.id === id);

  const clipIds = ['gaster', 'node1', 'node2', 'head'];
  const clip = clipIds
    .map((id) => byId(id))
    .filter((part): part is Part => part !== undefined)
    .map((part) => solidElement({ ...part, fill: undefined, monoStroke: undefined }))
    .join('\n      ');

  const solid = parts
    .filter((part) => part.monoSolid !== false)
    .map(solidElement)
    .join('\n        ');

  const grooves = parts
    .filter((part) => part.monoCut === 'clipToBody' && part.kind === 'path')
    .map((part) => `<path d="${(part as Extract<Part, { kind: 'path' }>).d}"/>`)
    .join('\n          ');

  // The coin's centre is not retyped here: it is read back from the same
  // `coin` part `icon-mark.svg` draws, so the mask's cuts can never drift from
  // the coin they are cut into.
  const coin = byId('coin');
  if (!coin || coin.kind !== 'circle') {
    throw new Error('mascot("carrying") has no circular "coin" part to cut the coin mask from');
  }

  const cuts = [
    `<g transform="${COIN_TRANSFORM}">`,
    ...MONO_CUTS.coin.map(
      (cut) =>
        `  <circle cx="${coin.cx}" cy="${coin.cy}" r="${cut.r}" stroke-width="${cut.width}"/>`,
    ),
    '</g>',
    ...MONO_CUTS.seams.map((cut) => `<path d="${cut.d}" stroke-width="${cut.width}"/>`),
    `<g clip-path="url(#body)" stroke-width="${MONO_CUTS.legGroove}">`,
    `  ${grooves}`,
    '</g>',
    ...MONO_CUTS.face.map((cut) => `<path d="${cut.d}" stroke-width="${cut.width}"/>`),
  ].join('\n        ');

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="1024" height="1024">`,
    '  <!-- Generated by scripts/render-icons.ts from src/design/mascot.ts. Do not edit. -->',
    '  <defs>',
    '    <clipPath id="body">',
    `      ${clip}`,
    '    </clipPath>',
    '  </defs>',
    '  <mask id="mark" maskUnits="userSpaceOnUse" x="0" y="0" width="1024" height="1024">',
    `    <g transform="${transform}">`,
    '      <g fill="#FFFFFF" stroke="#FFFFFF" stroke-linecap="round" stroke-linejoin="round">',
    `        ${solid}`,
    '      </g>',
    '      <g fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round">',
    `        ${cuts}`,
    '      </g>',
    '    </g>',
    '  </mask>',
    '  <rect width="1024" height="1024" fill="#000000" mask="url(#mark)"/>',
    '</svg>',
    '',
  ].join('\n');
}
